from .generate_damage_processor import GenerateDamageSingleProcessor as GenerateDamageProcessor
from .perform_damage_processor import PerformDamageSingleProcessor as PerformDamageProcessor
from .remove_flag_was_damaged_by_processor import RemoveFlagWasDamagedByProcessor
from .remove_flag_has_damaged_processor import RemoveFlagHasDamagedProcessor
from .remove_flag_is_about_to_be_damaged_by_processor import RemoveFlagIsAboutToBeDamagedByProcessor
from .remove_flag_has_no_health_processor import RemoveFlagHasNoHealthProcessor

from .perform_adjust_damaging_processor import PerformAdjustDamagingProcessor
from .remove_flag_adjust_damaging_processor import RemoveFlagAdjustDamagingProcessor