[messages]
default_ttl = 10_000

  [messages.on_events]
  ITEM_PICKUP = [
  "FROM JSON: {} was picked up by entity {}",
  [ "generator_obj", "other_obj" ]
]

[keys]
console_toggle = "K_F9"
save_game = "K_F5"
load_game = "K_F6"
pause_game = "K_p"

  [keys.key_controls_1]
  up = "K_u"
  down = "K_j"
  left = "K_h"
  right = "K_k"
  attack = "K_z"

[display]
resolution = [ 640, 480 ]
bitdepth = 32
fullscreen = false
max_fps = 1_200
show_fps = true

[debug]
show_health = true
show_state = true
show_weapons = true
show_wearables = true
show_inventory = true
show_labels = true
show_position = true
show_brain = true
show_collision = true
show_direction = true
show_map_screen_area = true

[console.global]
animation = [ "TOP", 2_000 ]
layout = "INPUT_BOTTOM"
padding = [ 0, 0, 0, 0 ]
bck_image = "quake.png"
bck_image_resize = true
bck_alpha = 150
welcome_msg = """
Welcome to pyRPG Console
***********************
Type 'exit' to quit
Type 'help'/'?' for help
Type '? shell' for examples of python commands"""
welcome_msg_color = [ 0, 255, 0 ]

[console.header]
text = "pyRPG Console v0.1 | {} | "
text_params = [ "cons_get_info_header" ]
layout = [ "SCROLL_LEFT_CONTINUOUS", 0, 0.5 ]
padding = [ 10, 10, 10, 10 ]
font_file = "IBMPlexMono-Regular.ttf"
font_size = 12
font_antialias = true
font_color = [ 255, 255, 255 ]
bck_alpha = 100

[console.output]
padding = [ 0, 0, 10, 10 ]
font_file = "IBMPlexMono-Regular.ttf"
font_size = 12
font_antialias = true
font_color = [ 255, 255, 255 ]
bck_alpha = 100
buffer_size = 100
display_lines = 30
display_columns = 90

[console.input]
padding = [ 0, 0, 10, 10 ]
font_file = "IBMPlexMono-Regular.ttf"
font_size = 12
font_antialias = true
font_color = [ 255, 0, 0 ]
bck_color = [ 0, 255, 0 ]
bck_alpha = 100
prompt = ">>>"
repeat_keys_interval_ms = 35

[console.footer]
text = "{}"
text_params = [ "cons_get_info_footer" ]
layout = [ "TEXT_RIGHT" ]
padding = [ 10, 10, 10, 10 ]
font_file = "IBMPlexMono-Regular.ttf"
font_size = 10
font_antialias = true
font_color = [ 255, 255, 255 ]
bck_alpha = 100
