from .generate_command_from_brain_processor import GenerateCommandFromBrainProcessor
from .generate_command_from_btree_processor import GenerateCommandFromBTreeProcessor
from .generate_command_from_blist_processor import GenerateCommandFromBListProcessor
from .generate_command_from_file_processor import GenerateCommandFromFileProcessor
from .generate_command_from_input_processor import GenerateCommandFromInputProcessor
from .generate_command_from_mouse_processor import GenerateCommandFromMouseProcessor

from .perform_command_processor import PerformCommandProcessor
from .perform_pathfinding_calculation_processor import PerformPathfindingCalculationProcessor
from .record_command_to_file_processor import RecordCommandToFileProcessor