__all__ = ['GenerateCommandFromInputProcessor']

import logging

# Parent super-class
from pyrpg.core.ecs.esper import Processor, SkipProcessorExecution

# Used components
from core.components.controllable import Controllable

# Logger init
logger = logging.getLogger(__name__)

class GenerateCommandFromInputProcessor(Processor):
    ''' Based on user input generates commands to controll the entity.

    Input parameters:
        -   events - list of pressed keys passed from the main game loop
        -   add_command_fnc - function for storing commands for later processing

    Involved components:
        -   Controllable

    Related processors:
        -   PerformCommandProcessor - for processing of commands generated by this processor

    What if this processor is disabled?
        -	game cannot be controlled by input peripherals

    Where the processor should be planned?
        -   before PerformCommandProcessor - before processing the commands from this processor
        -   as first of the processors - user input should have priority over AI (Brain)
    '''

    PREREQ = []

    def __init__(self, FNC_ADD_COMMAND, *args, **kwargs):
        ''' Initiation of NewInputProcessor processor.

        Parameters:
            :param add_command_fnc: Reference to the function that adds command to the command queue.
            :param add_command_fnc: reference
        '''
        super().__init__(*args, **kwargs)

        # Reference to function for adding to command queue
        self.add_command_fnc = FNC_ADD_COMMAND

    def initialize(self, register):
        '''Processor registers itself at esper ECS World'''
        register(self)

    def process(self, *args, **kwargs):
        ''' Process entities having Controllable component. Read user
        input and generate corresponding commands.
        '''
        try:
            super().process(*args, **kwargs)
        except SkipProcessorExecution:
            return

        """
        def _add_cmds_to_queue(cmd_list, ent, cmd_add_fnc):
            ''' Checks if entity is already part of the command. If not, fills owner of Controllable entity.
            Further adds the command to the queue.

            Parameters:
                :param cmd_list: List of commands (tuples) defined in Controllable component to be processed
                :type list:

                :param ent: Entity - owner of Controllable component to be added as parameter to the command
                            in case that entity is not already part of the command parameters from Controllable
                            component.
                :type ent: int

                :param cmd_queue: Queue to which the resulting commands are passed
                :type cmd_queue: reference to function
            '''

            # Perform every command in sequence - can be more than one defined in the list
            for cmd in cmd_list:
            
                #cmd_name, cmd_params = cmd

                # Ensure that proper 'entity' is passed as a command parameter - owner of Controllable component
                # if not stated otherwise
                #cmd_params = {**cmd[1], **{'entity' : ent}} if cmd[1].get('entity', None) is None else cmd[1]

                # Add command to the queue
                # cmd_queue.append((cmd[0], cmd_params))
                #cmd_add_fnc((cmd[0], cmd_params))
                #cmd_add_fnc((cmd_name, cmd_params), ent, None) 
                cmd_add_fnc(cmd, entity_id=ent, generator=None) 


                # debug
                logger.debug(f'({self.cycle}) - Entity {ent} - Command "{cmd}" added to the cmd queue.')
        """

        # Extract events and keys from parameter kwargs
        # currently only keys are used but events might be usefull as well for mouse later
        #events = kwargs.get('events', [])

        keys = kwargs.get('keys', [])
        
        # Get all entities that are controllable - not necesserilly moveable as the input can be for static entity theoretically
        for ent, (control) in self.world.get_component(Controllable):

            for cmd_str in ['UP', 'DOWN', 'LEFT', 'RIGHT', 'ATTACK']:
                
                # Check if the assigned key for the command was pressed
                if keys[control.control_keys.get(cmd_str)]:
                    # Add all associated commands to the command queue
                    #_add_cmds_to_queue(inp.control_cmds.get(cmd_str), ent, self.add_command_fnc)
                    #for cmd_name, cmd_params in control.control_cmds.get(cmd_str):
                    for cmd in control.control_cmds.get(cmd_str):
                        self.add_command_fnc(
                            cmd=cmd,
                            orig_entity_id=ent # notice there here not passing info about generator
                        )

                        logger.debug(f'({self.cycle}) - Entity {ent} - "{cmd=}" sent to the command manager - from input.')


    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components (none)
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        pass
