__all__ = ['GenerateCommandFromFileProcessor']

import logging
import json

# Parent super-class
from pyrpg.core.ecs.esper import Processor, SkipProcessorExecution
from pyrpg.core.commands import Command

# Logger init
logger = logging.getLogger(__name__)

class GenerateCommandFromFileProcessor(Processor):
    ''' Performs commands stored in the file.

    Involved components:
        -   None

    Related processors:
        -   PerformCommandProcessor - for processing of commands generated by this processor

    What if this processor is disabled?
        -   commands from file are not processed in the game

    Where the processor should be planned?
        -   before PerformCommandProcessor - before processing the commands from this processor
        -   before GenerateCommandFromBrainProcessor - as some commands in the file can modify Brain
        -   after GenerateCommandFromInputProcessor - if we want to make sure that input commands are disabled
    '''

    # Processors that need to be planned before this processor in order for it to work.
    PREREQ = []

    def __init__(self, FNC_ADD_COMMAND, FNC_CLEAR_COMMANDS, file, *args, mode='total_control', **kwargs):
        ''' Init the processor.

        Parameters:
            :param FNC_ADD_COMMAND: Reference to the function that adds command to the command queue.
            :param FNC_ADD_COMMAND: reference

            :param FNC_CLEAR_COMMANDS: Reference to the function that clears all commands from the command queue.
            :param FNC_CLEAR_COMMANDS: reference

            :param file: Path to the file with stored commands.
            :param file: str

            :param mode: 'append' mode keeps the already existing commands in the queue
                         'overwrite' mode overwrites the command queue only in defined cycles
                         'total_control' overwrite the queue with empty command list in case that 
                            no commands are available for the cycle and hence totaly disables input.
            :param type: str
        '''

        super().__init__(*args, **kwargs)

        # Reference to function for adding to command queue
        self.add_command_fnc = FNC_ADD_COMMAND

        # Reference to function for clearing command queue
        self.clear_commands_fnc = FNC_CLEAR_COMMANDS
        
        # File handler
        self.fh = open(file, 'r')

        # Counter of process cycles - increases every time processor runs
        self.cycle_counter = 0

        # Set booleans to control when and how the command queue needs to be overwritten
        self.overwrite = True if mode.lower() in ('overwrite', 'total_control') else False
        self.total_control = True if mode.lower() in ('total_control') else False

        # Store the nearest cycle and command
        self.next_rec = self._read_next_line()

    def _read_next_line(self):
        next_rec = self.fh.readline()
        if next_rec:
            return (json.loads(next_rec).get('cycle'), json.loads(next_rec).get('commands'))
        else:
            return None


    def process(self, *args, **kwargs):
        ''' Insert commands from the file to the queue based on the cycle number.
        '''
        try:
            super().process(*args, **kwargs)
        except SkipProcessorExecution:
            return

        logger.debug(f'({self.cycle}) - Processing Cycle: {self.cycle_counter}')

        # If there is next record in the file
        if self.next_rec:

            # Check if the record in the file is for execution in this cycle run
            if self.cycle_counter == self.next_rec[0]: # cycle

                # If in overwrite mode, clear the command queue before inserting commands from the file
                if self.overwrite:
                    self.clear_commands_fnc()
                
                # Insert commands from the file for the given cycle
                for cmd in self.next_rec[1]: # command queue 
                    command, entity_id, generator = cmd
                    self.add_command_fnc(Command(command[0], command[1], command[2]), entity_id, generator)
                    logger.debug(f'({self.cycle}) - Adding command "{command}" from file into the cycle {self.cycle_counter}.')

                # Read the next record
                self.next_rec = self._read_next_line()

            else:
                # In case of total control delete the queue always until there is something in the file
                if self.total_control:
                    self.clear_commands_fnc()

            # Increase cycle counter always if there is something in the file
            self.cycle_counter += 1

    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        # Close the file
        self.fh.close()
