__all__ = ['GenerateCommandFromInputProcessor']

import logging
import pygame

# Parent super-class
from pyrpg.core.ecs import Processor, SkipProcessorExecution

# Used components
from core.components.controllable import Controllable

from pyrpg.core.config import KEYS

# Logger init
logger = logging.getLogger(__name__)

class GenerateCommandFromInputProcessor(Processor):
    ''' Based on user input generates commands to controll the entity.

    Input parameters:
        -   events - list of pressed keys passed from the main game loop
        -   add_command_fnc - function for storing commands for later processing

    Involved components:
        -   Controllable

    Related processors:
        -   PerformCommandProcessor - for processing of commands generated by this processor

    What if this processor is disabled?
        -	game cannot be controlled by input peripherals

    Where the processor should be planned?
        -   before PerformCommandProcessor - before processing the commands from this processor
        -   as first of the processors - user input should have priority over AI (Brain)
    '''

    PREREQ = []

    def __init__(self, FNC_ADD_COMMAND, *args, **kwargs):
        ''' Initiation of NewInputProcessor processor.

        Parameters:
            :param add_command_fnc: Reference to the function that adds command to the command queue.
            :param add_command_fnc: reference
        '''
        super().__init__(*args, **kwargs)

        # Reference to function for adding to command queue
        self.add_command_fnc = FNC_ADD_COMMAND

    def _add_commands_to_queue(self, ent: int, cmds: list, desc: str=None) -> None:
        '''Adds commands fromthe list to the command queue.

            :param ent: Entity Id of the entity passing the commands to the command queue
            :type ent: int

            :param cmds: List of commands
            :type cmds: list

            :param desc: Additional description for logging
            :type desc: str | None
        '''

        # Notice that it is not passing info about generator
        for cmd in cmds: 
            self.add_command_fnc(cmd=cmd, orig_entity_id=ent)
            logger.debug(f'({self.cycle}) - Entity {ent} - "{cmd=}" sent to the command manager - from input. {desc}')


    def process(self, *args, **kwargs):
        ''' Process entities having Controllable component. Read user
        input and generate corresponding commands.
        '''
        try:
            super().process(*args, **kwargs)
        except SkipProcessorExecution:
            return

        # Extract events and keys from parameter kwargs
        keys = kwargs.get('keys', [])
        events = kwargs.get('events', [])

        # Get all entities that are controllable - not necesserilly moveable as the input can be for static entity theoretically
        for ent, (control) in self.world.get_component(Controllable):

            # Check all potential keys (command definitions) for activation - 'UP', 'DOWN', 'LEFT', 'RIGHT', etc...
            for cmd_str in control.control_cmds.keys():

                # Get the actual key code to determine if key is pressed
                key_code = control.control_keys[cmd_str]

                # Get the activation mode on the key (holding key, press released, press)
                #key_feedback_mod = KEYS["KEY_FEEDBACK"].get(cmd_str, 'HOLD')
                key_feedback_mod = control.key_feedback[cmd_str]

                # Activation by holding - default
                if keys[key_code] and key_feedback_mod == 'HOLD':
                    self._add_commands_to_queue(ent=ent, cmds=control.control_cmds.get(cmd_str), desc=key_feedback_mod)

                # Activation at the moment of pressing / releasing the key
                elif key_feedback_mod in ['UP', 'DOWN']:

                    for event in events:
                        if (event.type == pygame.KEYDOWN and event.key == key_code and key_feedback_mod == 'DOWN') or \
                           (event.type == pygame.KEYUP and event.key == key_code and key_feedback_mod == 'UP'):

                            self._add_commands_to_queue(ent=ent, cmds=control.control_cmds.get(cmd_str), desc=key_feedback_mod)


    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components (none)
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        pass
