''' Module "example_game.core.components.flag_generated_from_factory" contains
FlagGeneratedFromFactory component implemented as a FlagGeneratedFromFactory class.

Use 'python -m example_game.core.components.flag_generated_from_factory -v' to run
module tests.
'''

from pyrpg.core.ecs import Component

class FlagGeneratedFromFactory(Component):
    ''' Entity has been generated by factory.

    Used by:
        -   PerformFactoryGenerationProcessor
        -   NewPerformFactoryGeneratedPositionAdjustmentProcessor
        -   NewPerformFactoryGeneratedCollisionAdjustmentProcessor
        -   NewPerformFactoryGeneratedMovementAdjustmentProcessor
    '''

    __slots__ = []

    def __init__(self):
        ''' Initiate values for the new FlagGeneratedFromFactory component.
        '''
        super().__init__()

if __name__ == '__main__':
    import doctest
    doctest.testmod()
