# Arming
from .generate_arm_weapon_processor import GenerateArmWeaponProcessor
from .perform_arm_weapon_processor import PerformArmWeaponProcessor
from .perform_set_weapon_into_use_processor import PerformSetWeaponIntoUseProcessor

from .remove_flag_has_armed_weapon_processor import RemoveFlagHasArmedWeaponProcessor
from .remove_flag_is_about_to_arm_weapon_processor import RemoveFlagIsAboutToArmWeaponProcessor
from .remove_flag_was_armed_as_weapon_by_processor import RemoveFlagWasArmedAsWeaponByProcessor

# Disarming
from .generate_disarm_weapon_processor import GenerateDisarmWeaponProcessor
from .perform_disarm_weapon_processor import PerformDisarmWeaponProcessor
from .remove_flag_has_disarmed_weapon_processor import RemoveFlagHasDisarmedWeaponProcessor
from .remove_flag_is_about_to_disarm_weapon_processor import RemoveFlagIsAboutToDisarmWeaponProcessor
from .remove_flag_was_disarmed_as_weapon_by_processor import RemoveFlagWasDisarmedAsWeaponByProcessor
