from .generate_sound_fx_on_arm_weapon_processor import GenerateSoundFXOnArmWeaponProcessor
from .generate_sound_fx_on_collision_processor import GenerateSoundFXOnCollisionProcessor
from .generate_sound_fx_on_creation_processor import GenerateSoundFXOnCreationProcessor
from .generate_sound_fx_on_damage_processor import GenerateSoundFXOnDamageProcessor
from .generate_sound_fx_on_generation_processor import GenerateSoundFXOnGenerationProcessor
from .generate_sound_fx_on_no_health_processor import GenerateSoundFXOnNoHealthProcessor

from .generate_visual_fx_on_collision_processor import GenerateVisualFXOnCollisionProcessor
from .generate_visual_fx_on_creation_processor import GenerateVisualFXOnCreationProcessor
from .generate_visual_fx_on_damage_processor import GenerateVisualFXOnDamageProcessor
from .generate_visual_fx_on_generation_processor import GenerateVisualFXOnGenerationProcessor
from .generate_visual_fx_on_no_health_processor import GenerateVisualFXOnNoHealthProcessor
