'''
	Example of model.json file - no prototype
	-> darkmale.png
	-> darkmale.json (fully generated by Tiled) - fully defines the model

	##########################################################
	{ "columns":13,
	"image":"darkmale.png",
	"imageheight":1344,
	"imagewidth":832,
	"margin":0,
	"name":"darkmale",
	"spacing":0,
	"tilecount":273,
	"tiledversion":"1.3.1",
	"tileheight":64,
	"tilewidth":64,
	"transparentcolor":"#000000",
	"type":"tileset",
	"version":1.2
	"tiles":[ 
		{
			"animation":[
					{
					"duration":101,
					"tileid":117
					}, 
					...],
			"id":117,
			"properties":[
					{
					"name":"action",
					"type":"string",
					"value":"walk"
					}, 
					{
					"name":"direction",
					"type":"string",
					"value":"left"
					}]
			},

	##########################################################

	-> input to renderable component
	-> {"type" : "RenderableModel", "params" : {"model" : "darkmale.json"}}
'''
import functools # for cache decorator
import json # necessary to parse json files
import ctypes # to show number of references to an instance


@functools.lru_cache(maxsize=32)#@Memoize
class RenderableModel(object):
	''' Entity is displayable on the game screen.

	Used by:
		-	RenderWorldProcessor
		-	RenderDebugProcessor

	Tests:
		>>> c = Renderable()
	'''

	__slots__ = ['texture_data', 'texture_length', 'texture_dynamic', 'name', 'model_name', 'last_frame', 'last_time', 'w', 'h', 'd_h', 'd_w']

	# Allowed model directions and actions
	DIRECTIONS = ['up', 'down', 'left', 'right']
	ACTIONS = ['walk']
	MODEL_PATH = 'experiments/ecs/resources/models/'
	TILE_RES = 64

	def __init__(self, *args, **kwargs):
		''' Initiate values for the new RenderableModel component.

		Parameters:
			:param model_name: Name of the model stored in MODEL_PATH directory
			:type model_name: str

			:raise: ValueError - in case model file is not found or has problem
		'''

		super().__init__()

		# Get the model name
		model_file = kwargs.get("model", "")

		# Check the model name
		try:
			assert isinstance(model_file, str), f'Model file name {model_file} is not valid.'
		except AssertionError:
			# Notify component factory that initiation has failed
			raise ValueError
		
		# Initiate variables
		self.name = None
		self.w = self.h = self.d_w = self.d_h = None

		self.texture_data = {'default' : [{'duration' : 0, 'tile' : None}]}
		self.texture_length = {'default' : 1}
		self.texture_dynamic = {'default' : False}

		# Time and frame must be remembered for animation
		self.last_frame = 0
		self.last_time = pygame.time.get_ticks()

		# Load model from model file
		try:
			self._load_model(model_file)
		except:
			# Notify component factory that initiation has failed
			raise ValueError

	def _load_model(self, model_file):
		''' Loads model - no prototyping is needed because entity can have prototype
		and part of this prototype can be RenderableModel.
		'''

		# Open the model json file
		try:		
			with open(RenderableModel.MODEL_PATH + model_file, 'r') as model_file:
				json_model_data = model_file.read()
				model_data = json.loads(json_model_data)
		except FileNotFoundError:
			print(f"Model file not found.")
			# Notify component factory that initiation has failed
			raise ValueError

		# Store name and dimensions of the model
		self.name = model_data.get('name')
		self.w = model_data.get('tilewidth')
		self.h = model_data.get('tileheight')

		# Diff vector from centre of the sprite to the topleft corner
		# it is used by Render processor to get the right point where
		# to render the sprite. i.e. position of the character can be 
		# 100, 100 but in order to be centered on this position, render 
		# processor must blit the sprite on 75,75 (example w,h=50)
		self.d_w = self.w / 2
		self.d_h = self.h / 2

		# Load image with all model tiles
		try:
			image = pygame.image.load(RenderableModel.MODEL_PATH + model_data.get('image', '')).convert()
		except AttributeError:
			print(f"Unexpected error while processing model file {model_data} not found.")
			raise ValueError

		# Set color for transparent key
		image.set_colorkey(pygame.Color(model_data.get('transparentcolor', '#000000')))

		# Read the picture data from texture file - necessary for saving tiles
		image_width = model_data.get('imagewidth', 0)
		image_height = model_data.get('imageheight', 0)

		#####
		# Store the default model picture to texture_data - at least one picture in the model
		#####

		# Prepare the tile texture - rectangle from the image - topleft image
		rect = ((0 % (image_width // self.w)) * self.w, 
				(0 // (image_width // self.h)) * self.h, 
				self.w, self.h)

		# Prepare the tile texture - image from model file - most topleft
		self.texture_data.update({'default' : [{'duration' : 0, 'tile' : pygame.transform.scale(image.subsurface(rect), [RenderableModel.TILE_RES, RenderableModel.TILE_RES])}]})

		#####
		# Store the animated tile textures if there are any
		#	- go through tiles list
		#	- ignore list items without key 'properties'
		#####
		
		# Go through the list of animated tiles
		for anim_tile in model_data.get('tiles', []):
			
			action = None
			direction = None

			# Process only those with allowed properties - saved in global class var
			for property in anim_tile.get('properties', []):
				
				# Store action and direction
				if property.get('name') == 'action': action = property.get('value')
				if property.get('name') == 'direction': direction = property.get('value')
					
				# Check that action and direction are valid and hence we can proceed with saving
				if action in RenderableModel.ACTIONS and direction in RenderableModel.DIRECTIONS:
					
					##
					# Save the animation
					#	- prepare the list that will be added to texture_data on position of action and direction
					##
					
					frames = []
					
					# Variable used to determine if the tile is auto-animated or static
					dynamic = False

					# Iterate all the animation frames for given action and direction
					for frame_dict in anim_tile.get('animation'):

						frame = {}
					
						dynamic = True if frame_dict.get('duration', 0) > 0 else dynamic

						frame.update({ 'duration' : frame_dict.get('duration', 0)})

						# Prepare the tile texture - rectangle from the image
						rect = ((int(frame_dict.get('tileid', 0)) % (image_width // self.w)) * self.w, 
								(int(frame_dict.get('tileid', 0)) // (image_width // self.h)) * self.h, 
								self.w, self.h)
							
						# Save the tile image converted to TILE_RESOLUTION of the game (config.TILE_RES)
						frame.update({ 'tile' : pygame.transform.scale(image.subsurface(rect), [64,64]) })

						# Now is the frame ready to be stored into the list
						frames.append(frame)
					
					##
					# Now we can store the whole state with texture details and the metadata
					##

					# Store action frames and duration
					if self.texture_data.get(action, None):
						self.texture_data.get(action).update( {direction : frames})
					else:
						self.texture_data.update( { action : {direction : frames} })

					# Store length of the frames
					if self.texture_length.get(action, None):
						self.texture_length.get(action).update( {direction : len(frames)})
					else:
						self.texture_length.update( { action : {direction : len(frames)} })

					# Store information about dynamic or static animation
					if self.texture_dynamic.get(action, None):
						self.texture_dynamic.get(action).update( {direction : dynamic})
					else:
						self.texture_dynamic.update( { action : {direction : dynamic} })

	def __str__(self, level=0):
		
		tabs = '\t' * level

		return f'{tabs}*Instance of {self.__class__.__name__} ({hex(id(self))}) [{ctypes.c_long.from_address(id(self)).value}]:\n\
				{tabs}\tname\t\t({hex(id(self.name))}) [{ctypes.c_long.from_address(id(self.name)).value}]:\t{self.name}\n\
				{tabs}\tw\t\t({hex(id(self.w))}) [{ctypes.c_long.from_address(id(self.w)).value}]:\t{self.w}\n\
				{tabs}\th\t\t({hex(id(self.h))}) [{ctypes.c_long.from_address(id(self.h)).value}]:\t{self.h}\n\
				{tabs}\ttex_data\t\t({hex(id(self.texture_data))}) [{ctypes.c_long.from_address(id(self.texture_data)).value}]:\t{self.texture_data}\n\
				{tabs}\ttex_length\t\t({hex(id(self.texture_length))}) [{ctypes.c_long.from_address(id(self.texture_length)).value}]:\t{self.texture_length}\n\
				{tabs}\ttex_dynamic\t\t({hex(id(self.texture_dynamic))}) [{ctypes.c_long.from_address(id(self.texture_dynamic)).value}]:\t{self.texture_dynamic}\n'

	def get_frame(self, action, direction):
		''' Get the current frame for display. It is taking into account animated frames
		'''

		# If action is animated - then shift based on time
		if self.texture_dynamic.get(action).get(direction):

			# Get the currect frame and check the duration
			duration_of_curr_frame = self.texture_data.get(action).get(direction)[self.last_frame].get('duration')
			current_time = pygame.time.get_ticks() 
		
			# if delay is greater move to the next frame and reset timer
			if current_time - self.last_time > duration_of_curr_frame:
				self.last_time = current_time
				self.last_frame = (self.last_frame + 1) % self.texture_length.get(action).get(direction)

		return self.texture_data.get(action).get(direction)[self.last_frame].get('tile')

	def set_next_frame(self, action, direction):
		''' Set the next frame for animation '''
		self.last_time = pygame.time.get_ticks() 
		self.last_frame = (self.last_frame + 1) % self.texture_length.get(action).get(direction)


if __name__ == '__main__':

	import pygame

	pygame.init()
	window = pygame.display.set_mode([640,480])
	
	sample_model_1 = RenderableModel(model='darkmale.json')
	sample_model_2 = RenderableModel(model='darkmale.json')

	print(sample_model_1)
	print(sample_model_2)

	print(RenderableModel.cache_info())

	running = True

	while running:

		window.fill((0,0,0))

		# Read the keys pressed, mouse, win resize etc.
		key_events = pygame.event.get()

		# Check for End Game
		for event in key_events:
			if event.type == pygame.QUIT:
				running = False
			elif event.type == pygame.KEYDOWN:
				if event.key == pygame.K_LEFT:
					sample_model_1.set_next_frame('walk', 'left')
					print(sample_model_1.last_frame)


		''' TEST 1
		# List all frames of certain action
		action = 'default'
		direction = 'right'

		# List of frames
		for num, frame in enumerate(sample_model_1.texture_data.get(action).get(direction)):
			window.blit(frame.get('tile'), (num*64,0))
		'''
		
		''' TEST 2
		# Animate walk up for sample_model_1
		action = 'walk'
		direction = 'down'

		# If action is animated - then shift based on time
		if sample_model_1.texture_dynamic.get(action).get(direction):

			# Get the currect frame and check the duration
			duration_of_curr_frame = sample_model_1.texture_data.get(action).get(direction)[sample_model_1.last_frame].get('duration')
			current_time = pygame.time.get_ticks() 
		
			# if delay is greater move to the next frame and reset timer
			if current_time - sample_model_1.last_time > duration_of_curr_frame:
				sample_model_1.last_time = current_time
				sample_model_1.last_frame = (sample_model_1.last_frame + 1) % sample_model_1.texture_length.get(action).get(direction)


		window.blit(sample_model_1.texture_data.get(action).get(direction)[sample_model_1.last_frame].get('tile'), (0,0))
		'''

		''' TEST 3
		# Animate walk left for sample_model_1
		window.blit(sample_model_1.get_frame('walk','left'), (0,0))
		'''

		''' TEST 4 - 
		'''
		window.blit(sample_model_1.get_frame('walk','left'), (0,0))


		pygame.display.flip()

pygame.quit()
