__all__ = ['NewPerformFactoryGenerationProcessor']

import logging
import pyrpg.core.ecs.esper as esper	# for esper.Processor - parent class of all processors
import pyrpg.core.ecs.components as components # for definition of components

# Logger init
logger = logging.getLogger(__name__)

class NewPerformFactoryGenerationProcessor(esper.Processor):
    ''' Detects Factory entities that should generate entities
    (have the necessary data) and creates these entities.

    Involved components:
        -   NewFlagCreateFromFactory
        -   Factory

    Related processors:
        -   NewGenerateProjectileFactoryDataProcessor - processor that generates NewFlagCreateFromFactory

    What if this processor is disabled?
        -   entities (e.g. projectiles) are not generated from factories

    Where the processor should be planned?
        -   after NewGenerateProjectileFactoryDataProcessor
    '''

    # Processors that need to be planned before this processor in order for it to work.
    PREREQ = [
        ('new.attack_system.new_generate_projectile_factory_data_processor', 'NewGenerateProjectileFactoryDataProcessor')
        ]

    __slots__ = ['create_entity_fnc']

    def __init__(self, create_entity_fnc=None):
        ''' Init the processor.
        '''
        super().__init__()

        self.create_entity_fnc = create_entity_fnc

    def initialize(self, register):
        '''Processor registers itself at esper ECS World'''
        register(self)

    def process(self, *args, **kwargs):
        ''' Get all Factory components that should generate the entity
        and generate the entity into the world.
        '''
        self.cycle += 1


        for ent, (factory, flag_create_from_factory) in self.world.get_components(components.NewFactory, components.NewFlagCreateFromFactory):

            # Prepare new entity from factory
            new_entity = self.create_entity_fnc(
                factory.prescription,

                # New ID for new Entity
                entity_id=f'ORIG_ID:{factory.prescription.get("id", "")}:SUFF_ID:{flag_create_from_factory.id_suffix}:FACT_ENT:{ent}',

                # Register in the world if prescribed
                register=flag_create_from_factory.register
            )

            # Adjust the position component
            self.world.add_component(
                new_entity,
                components.Position(
                    x=flag_create_from_factory.position[0],
                    y=flag_create_from_factory.position[1],
                    dir_name=flag_create_from_factory.position[2],
                    map=flag_create_from_factory.position[3]
                )
            )

            # Log information about successful generation
            logger.debug(f'({self.cycle}) - Entity {new_entity} was generated by factory {ent}.')
            logger.debug(f'({self.cycle}) - Entity {new_entity} created on the following position: x={flag_create_from_factory.position[0]}, y={flag_create_from_factory.position[1]}, dir_name={flag_create_from_factory.position[2]}, map={flag_create_from_factory.position[3]}')

    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        pass
