__all__ = ['PerformFactoryGenerationProcessor']

import logging

# Parent super-class
from pyrpg.core.ecs.esper import Processor

# Used components
from pyrpg.core.ecs.components.new.flag_create_from_factory import FlagCreateFromFactory
from pyrpg.core.ecs.components.new.flag_generated_from_factory import FlagGeneratedFromFactory
from pyrpg.core.ecs.components.new.factory import Factory
from pyrpg.core.ecs.components.new.position import Position
from pyrpg.core.ecs.components.new.flag_adjust_collidable import FlagAdjustCollidable
from pyrpg.core.ecs.components.new.flag_adjust_movement import FlagAdjustMovement
from pyrpg.core.ecs.components.new.flag_adjust_damaging import FlagAdjustDamaging


# Logger init
logger = logging.getLogger(__name__)

class PerformFactoryGenerationProcessor(Processor):
    ''' Detects Factory entities that should generate entities
    (have the necessary data) and creates these entities.

    Involved components:
        -   FlagCreateFromFactory
        -   Factory
        -   Position

    Related processors:
        -   GenerateProjectileFactoryDataProcessor - processor that generates FlagCreateFromFactory

    What if this processor is disabled?
        -   entities (e.g. projectiles) are not generated from factories

    Where the processor should be planned?
        -   after GenerateProjectileFactoryDataProcessor
    '''

    # Processors that need to be planned before this processor in order for it to work.
    PREREQ = [
        'new.attack_system.generate_projectile_factory_data_processor:GenerateProjectileFactoryDataProcessor'
    ]

    __slots__ = ['create_entity_fnc']

    def __init__(self, create_entity_fnc=None):
        ''' Init the processor.
        '''
        super().__init__()

        self.create_entity_fnc = create_entity_fnc

    def initialize(self, register):
        '''Processor registers itself at esper ECS World'''
        register(self)

    def process(self, *args, **kwargs):
        ''' Get all Factory components that should generate the entity 
        and generate the entity into the world.
        '''
        self.cycle += 1

        for ent, (factory, flag_create_from_factory) in self.world.get_components(Factory, FlagCreateFromFactory):

            # Prepare new entity from factory
            new_entity = self.create_entity_fnc(
                factory.prescription,
                # New ID for new Entity
                entity_id=f'ORIG_ID:{factory.prescription.get("id", "")}:SUFF_ID:{flag_create_from_factory.id_suffix}:FACT_ENT:{ent}',
                # Register in the world if prescribed
                register=flag_create_from_factory.register
            )

            # Add FlagGeneratedFromFactory to the new entity
            self.world.add_component(new_entity, FlagGeneratedFromFactory())

            # Log information about successful generation
            logger.debug(f'({self.cycle}) - Entity {new_entity} was generated by factory {ent}.')

            # If position change was part of the FlagCreateFromFactory then do it
            if flag_create_from_factory.adjust_position:
                logger.debug(f'({self.cycle}) - Entity {new_entity} will be created on the following positions: {flag_create_from_factory.adjust_position}')

                # Adjust the position component
                self.world.add_component(
                    new_entity,
                    Position(**flag_create_from_factory.adjust_position)
                )
                # Log information about successful positioning
                logger.debug(f'({self.cycle}) - Entity {new_entity} created on the following position: x={flag_create_from_factory.adjust_position["x"]}, y={flag_create_from_factory.adjust_position["y"]}, dir_name={flag_create_from_factory.adjust_position["dir_name"]}, map={flag_create_from_factory.adjust_position["map"]}')

            # if collision adjustment was part of the FlagCreateFromFactory then do it
            if flag_create_from_factory.adjust_collision:
                self.world.add_component(
                    new_entity,
                    FlagAdjustCollidable(**flag_create_from_factory.adjust_collision)
                )
                # Log information about successful generation
                logger.debug(f'({self.cycle}) - Entity {new_entity} will have adjustment in its collision component.')

            # if movement adjustment was part of the FlagCreateFromFactory then do it
            if flag_create_from_factory.adjust_movement:
                self.world.add_component(
                    new_entity,
                    FlagAdjustMovement(**flag_create_from_factory.adjust_movement)
                )
                # Log information about successful generation
                logger.debug(f'({self.cycle}) - Entity {new_entity} will have adjustment in its movement component.')

            # if damaging adjustment was part of the FlagCreateFromFactory then do it
            if flag_create_from_factory.adjust_damaging:
                self.world.add_component(
                    new_entity,
                    FlagAdjustDamaging(**flag_create_from_factory.adjust_damaging)
                )
                # Log information about successful generation
                logger.debug(f'({self.cycle}) - Entity {new_entity} will have adjustment in its damaging component.')


    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        pass
