from .generate_score_on_damage_processor import GenerateScoreOnDamageProcessor
from .generate_score_on_no_health_processor import GenerateScoreOnNoHealthProcessor
from .calculate_score_processor import CalculateScoreProcessor
from .remove_flag_has_scored_processor import RemoveFlagHasScoredProcessor