''' Module "pyrpg.core.ecs.components.flag_create_from_factory" contains
FlagCreateFromFactory component implemented as a FlagCreateFromFactory class.

Use 'python -m pyrpg.core.ecs.components.flag_create_from_factory -v' to run
module tests.
'''

from pyrpg.core.ecs.components.component import Component

class FlagCreateFromFactory(Component):
    ''' Flag/tag to create new entity generated by the
    Factory component and enriched by the position component

    Used by:
        - PrepareProjectileProcessor
        - CreateEntityOnPositionProcessor

    Examples of JSON definition:
        {"type" : "FlagCreateFromFactory", 
         "params" : { 
             "position" : {
                 "x" : 20,
                 "y" : 20,
                 "dir" : "left",
                 "map" : "test_map"
             },
             "parent" : 5
          }
        }

    Tests:
        >>> c = FlagCreateFromFactory()
        >>> c.position
        None
        >>> c = FlagCreateFromFactory(**{"position" : {"x" : 20, "y" : 20}})
        >>> c.position['x']
        20
    '''

    __slots__ = ['position', 'parent', 'register', 'score', 'id_suffix', 'adjust_col']

    def __init__(self, *args, **kwargs):
        ''' Initiate values for the new FlagCreateFromFactory component.

        Parameters:
            :param position: Position where the new entity must be generated
            :type position: dict

            :param parent: Link to the parent entity
            :type parent: int

            :param register: Should the entity be globally registered with engine
            :type register: bool

            :param score: Should the entity have link to the parent score component
            :type score: bool

            :param id_suffix: Text that is added to Factory prescription entity ID during generation.
            :type id_suffix: str

            :raise: ValueError - in case of incorrect position/parent
        '''

        super().__init__()

        self.position = kwargs.get('position', None)
        self.parent = kwargs.get('parent', None)
        self.register = kwargs.get('register', False)
        self.score = kwargs.get('score', False)
        self.id_suffix = kwargs.get('id_suffix', '')
        self.adjust_col = kwargs.get('adjust_col', False)

        try:
            assert (isinstance(self.position, dict) and self.position != {}) or self.position is None, f'Parameter "position" must be passed as a defined dictionary.'
            assert isinstance(self.position.get('x'), int) and isinstance(self.position.get('y'), int), f'Parameter "position" must be passed with correct values.'
            assert isinstance(self.adjust_col, bool), f'Parameter "adjust_col" must be a boolean.'
            assert isinstance(self.parent, int) or self.parent is None, f'Parameter "parent" must be integer representing parent entity.'
            assert isinstance(self.register, bool), f'Parameter "register" must be a boolean.'
            assert isinstance(self.score, bool), f'Parameter "score" must be a boolean.'
            assert isinstance(self.id_suffix, str), f'Parameter "id_suffix" must be a string.'
        except AssertionError:
            # Notify component factory that initiation has failed
            raise ValueError


if __name__ == '__main__':
    import doctest
    doctest.testmod()

