from .perform_factory_generation_processor import PerformFactoryGenerationProcessor
from .remove_flag_create_from_factory_processor import RemoveFlagCreateFromFactoryProcessor
from .remove_flag_generated_from_factory_processor import RemoveFlagGeneratedFromFactoryProcessor