'''
TODO - rework ... all images store in image list not in the dictionary
TODO - static frames with properties and with no animation - save them correctly
TODO - texture_actions anre incorrectly filled
TODO - idle action is mandatory

	Example of model.json file - no prototype
	-> darkmale.png
	-> darkmale.json (fully generated by Tiled) - fully defines the model

	##########################################################
	{ "columns":13,
	"image":"darkmale.png",
	"imageheight":1344,
	"imagewidth":832,
	"margin":0,
	"name":"darkmale",
	"spacing":0,
	"tilecount":273,
	"tiledversion":"1.3.1",
	"tileheight":64,
	"tilewidth":64,
	"transparentcolor":"#000000",
	"type":"tileset",
	"version":1.2
	"tiles":[ 
		{
			"animation":[
					{
					"duration":101,
					"tileid":117
					}, 
					...],
			"id":117,
			"properties":[
					{
					"name":"action",
					"type":"string",
					"value":"walk"
					}, 
					{
					"name":"direction",
					"type":"string",
					"value":"left"
					}]
			},

	##########################################################

	-> input to renderable component
	-> {"type" : "RenderableModel", "params" : {"model" : "darkmale.json"}}
'''
import pygame
import functools # for cache decorator
import json # necessary to parse json files
import ctypes # to show number of references to an instance
import pyrpg.core.config.config as config # for model path

@functools.lru_cache(maxsize=32)#@Memoize
class Model(object):
	''' Animated model of entity
	'''

	__slots__ = ['texture_data', 'texture_length', 'texture_dynamic', 'texture_actions', 'name', 'model_file','w', 'h', 'd_h', 'd_w', 'no_tile']

	# Allowed model directions and actions
	DIRECTIONS = ['up', 'down', 'left', 'right']
	ACTIONS = ['default', 'walk', 'idle', 'idle_stab', 'stab', 'idle_swing', 'swing', 'shoot', 'idle_shoot', 'expire']

	def __init__(self, model_file):
		''' Initiate values for the new RenderableModel component.

		Parameters:
			:param model_file: Path to the model json file
			:type model_file: str

			:raise: ValueError - in case model file is not found or has problem
		'''

		super().__init__()

		# Get the model name
		self.model_file = model_file
		
		# Initiate variables
		self.name = None
		self.w = self.h = config.TILE_RES
		self.d_w = self.d_h = config.TILE_RES / 2

		self.texture_data = {'default' : [{'duration' : 0, 'tile' : None}]}
		self.texture_length = {'default' : 1}
		self.texture_dynamic = {'default' : False}
		self.texture_actions = set('default')

		# No tile is used in case tile for given action / direction / frame is not found
		# see RenderableModel.get_frame
		self.no_tile = pygame.Surface((0,0))

		# Load model from model file
		try:
			self._load_model(config.MODEL_PATH / self.model_file)
		except:
			# Notify component factory that initiation has failed
			raise ValueError

	def _load_model(self, model_path):
		''' Loads model - no prototyping is needed because entity can have prototype
		and part of this prototype can be RenderableModel.
		'''

		# Open the model json file
		try:		
			with open(model_path, 'r') as model_file:
				json_model_data = model_file.read()
				model_data = json.loads(json_model_data)
		except FileNotFoundError:
			print(f"Model file {model_path} not found.")
			# Notify component factory that initiation has failed
			raise ValueError

		# Store name and dimensions of the model
		self.name = model_data.get('name')
		tilewidth = model_data.get('tilewidth')
		tileheight = model_data.get('tileheight')

		# Diff vector from centre of the sprite to the topleft corner
		# it is used by Render processor to get the right point where
		# to render the sprite. i.e. position of the character can be 
		# 100, 100 but in order to be centered on this position, render 
		# processor must blit the sprite on 75,75 (example w,h=50)
		#self.d_w = self.w / 2
		#self.d_h = self.h / 2

		# Load image with all model tiles
		try:
			image = pygame.image.load(str(config.MODEL_PATH / model_data.get('image', ''))).convert()
		except AttributeError:
			print(f"Unexpected error while processing model file {model_data} not found.")
			raise ValueError

		# Set color for transparent key
		image.set_colorkey(pygame.Color(model_data.get('transparentcolor', '#000000')))

		# Read the picture data from texture file - necessary for saving tiles
		image_width = model_data.get('imagewidth', 0)

		#####
		# Store the default model picture to texture_data - at least one picture in the model
		#####

		# Prepare the tile texture - rectangle from the image - topleft image
		rect = ((0 % (image_width // tilewidth)) * tilewidth, 
				(0 // (image_width // tileheight)) * tileheight, 
				tilewidth, tileheight)

		# Prepare the tile texture - image from model file - most topleft
		self.texture_data.update({'default' : [{'duration' : 0, 'tile' : pygame.transform.scale(image.subsurface(rect), [config.TILE_RES, config.TILE_RES])}]})

		#####
		# Store the animated tile textures if there are any
		#	- go through tiles list
		#	- ignore list items without key 'properties'
		#####
		
		# Go through the list of animated tiles
		for anim_tile in model_data.get('tiles', []):
			
			action = None
			direction = None

			# Process only those with allowed properties - saved in global class var
			for property in anim_tile.get('properties', []):
				
				# Store action and direction
				if property.get('name') == 'action': action = property.get('value')
				if property.get('name') == 'direction': direction = property.get('value')
					
				# Check that action and direction are valid and hence we can proceed with saving
				if action in Model.ACTIONS and direction in Model.DIRECTIONS:
					
					## Record that action is supported
					self.texture_actions.add(action)

					##
					# Save the animation
					#	- prepare the list that will be added to texture_data on position of action and direction
					##
					
					frames = []
					
					# Variable used to determine if the tile is auto-animated or static
					dynamic = False

					# Check if tile is static (one tile) or animation
					if not anim_tile.get('animation', None):
						# if static, save diferently

						frame = {'duration' : 0}

						# Prepare the tile texture - rectangle from the image
						rect = ((int(anim_tile.get('id', 0)) % (image_width // tilewidth)) * tilewidth, 
								(int(anim_tile.get('id', 0)) // (image_width // tileheight)) * tileheight, 
								tilewidth, tileheight)

						# Save the tile image converted to TILE_RESOLUTION of the game (config.TILE_RES)
						frame.update({ 'tile' : pygame.transform.scale(image.subsurface(rect), [config.TILE_RES, config.TILE_RES]) })
						
						frames.append(frame)
					
					else:
						# Iterate all the animation frames for given action and direction
						for frame_dict in anim_tile.get('animation'):

							frame = {}
						
							dynamic = True if frame_dict.get('duration', 0) > 0 else dynamic

							frame.update({ 'duration' : frame_dict.get('duration', 0)})

							# Prepare the tile texture - rectangle from the image
							rect = ((int(frame_dict.get('tileid', 0)) % (image_width // tilewidth)) * tilewidth, 
									(int(frame_dict.get('tileid', 0)) // (image_width // tileheight)) * tileheight, 
									tilewidth, tileheight)
								
							# Save the tile image converted to TILE_RESOLUTION of the game (config.TILE_RES)
							frame.update({ 'tile' : pygame.transform.scale(image.subsurface(rect), [config.TILE_RES, config.TILE_RES]) })

							# Now is the frame ready to be stored into the list
							frames.append(frame)
						
					##
					# Now we can store the whole state with texture details and the metadata
					##

					# Store action frames and duration
					if self.texture_data.get(action, None):
						self.texture_data.get(action).update( {direction : frames})
					else:
						self.texture_data.update( { action : {direction : frames} })

					# Store length of the frames
					if self.texture_length.get(action, None):
						self.texture_length.get(action).update( {direction : len(frames)})
					else:
						self.texture_length.update( { action : {direction : len(frames)} })

					# Store information about dynamic or static animation
					if self.texture_dynamic.get(action, None):
						self.texture_dynamic.get(action).update( {direction : dynamic})
					else:
						self.texture_dynamic.update( { action : {direction : dynamic} })

	def __str__(self, level=0):
		
		tabs = '\t' * level

		return f'{tabs}*Instance of {self.__class__.__name__} ({hex(id(self))}) [{ctypes.c_long.from_address(id(self)).value}]:\n\
				{tabs}\tname\t\t({hex(id(self.name))}) [{ctypes.c_long.from_address(id(self.name)).value}]:\t{self.name}\n\
				{tabs}\tw\t\t({hex(id(self.w))}) [{ctypes.c_long.from_address(id(self.w)).value}]:\t{self.w}\n\
				{tabs}\th\t\t({hex(id(self.h))}) [{ctypes.c_long.from_address(id(self.h)).value}]:\t{self.h}\n\
				{tabs}\ttex_data\t\t({hex(id(self.texture_data))}) [{ctypes.c_long.from_address(id(self.texture_data)).value}]:\t{self.texture_data}\n\
				{tabs}\ttex_length\t\t({hex(id(self.texture_length))}) [{ctypes.c_long.from_address(id(self.texture_length)).value}]:\t{self.texture_length}\n\
				{tabs}\ttex_dynamic\t\t({hex(id(self.texture_dynamic))}) [{ctypes.c_long.from_address(id(self.texture_dynamic)).value}]:\t{self.texture_dynamic}\n\
				{tabs}\ttex_actions\t\t({hex(id(self.texture_actions))}) [{ctypes.c_long.from_address(id(self.texture_actions)).value}]:\t{self.texture_actions}\n'
