__all__ = ['InputProcessor']

import pyrpg.core.ecs.esper as esper	# for esper.Processor - parent class of all processors
import pyrpg.core.ecs.components as components # for definition of components
import pyrpg.core.config.config as config # for MOVE_SPEED


class InputProcessor(esper.Processor):
    ''' Based on user input generates commands to controll the entity.
    
    Input parameters:
        -	events - list of pressed keys passed from the main game loop
        -	input_command_queue - queue for storing commands for later processing
        -	debug

    Involved components:
        -	Controllable
    
    Related processors:
        -	CommandProcessor - for processing of commands generated by this processor

    What if this processor is disabled?
        -	game cannot be controlled by keyboard
    
    Where the processor should be planned?
        -	before CommandProcessor - before processing the commands from this processor
        -	as first of the processors - user input should have priority over AI (Brain)
    '''

    def __init__(self, input_command_queue, debug=False):
        ''' Initiation of InputProcessor processor.
        '''
        super().__init__()
        self.input_command_queue = input_command_queue
        self.debug = debug

    def initialize(self, register):
        '''Processor registers itself at esper ECS World'''
        register(self)

    def process(self, *args, **kwargs):
        ''' Process entities having Controllable and Motion components. Read user
        input and generate corresponding commands and add them to the command queue.
        '''
        
        # Extract events and keys from parameter kwargs
        # currently only keys are used but events might be usefull as well for mouse later
        #events = kwargs.get('events', [])
        
        keys = kwargs.get('keys', [])

        # Get all entities that are controllable - not necesserilly moveable as the input can be for static entity theoretically
        for ent, (inp) in self.world.get_component(components.Controllable):

            # For each entity check if control keys were pressed and move them accordingly
            # only process if keys are enabled.
            if inp.enabled:

                # Move up
                if keys[inp.control_keys.get('up')]:
                    self.input_command_queue.append((inp.control_cmds.get('up'), {"entity" : ent, "dy" : -config.MOVE_SPEED}))

                # Move down
                if keys[inp.control_keys.get('down')]:
                    self.input_command_queue.append((inp.control_cmds.get('down'), {"entity" : ent, "dy" : config.MOVE_SPEED}))

                # Move left
                if keys[inp.control_keys.get('left')]:
                    self.input_command_queue.append((inp.control_cmds.get('left'), {"entity" : ent, "dx" : -config.MOVE_SPEED}))

                # Move right
                if keys[inp.control_keys.get('right')]:
                    self.input_command_queue.append((inp.control_cmds.get('right'), {"entity" : ent, "dx" : config.MOVE_SPEED}))

                # Attack
                if keys[inp.control_keys.get('attack')]:
                    self.input_command_queue.append((inp.control_cmds.get('attack'), {"entity" : ent}))
                
                # If none above buttons are presed
                #if not (keys[inp.control_keys.get('up')]
                #	or keys[inp.control_keys.get('up')]
                #	or keys[inp.control_keys.get('up')]
                #	or keys[inp.control_keys.get('up')]):


    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components (none)
        '''
        pass

    def post_load(self, input_command_queue):
        ''' Reconfigure the processor after de-serialization by attaching
        the reference to window again
        '''
        self.input_command_queue = input_command_queue
