from .generate_teleportation_processor import GenerateTeleportationProcessor
from .perform_teleportation_processor import PerformTeleportationProcessor
from .remove_flag_has_teleported_processor import RemoveFlagHasTeleportedProcessor
from .remove_flag_is_about_to_be_teleported_by_processor import RemoveFlagIsAboutToBeTeleportedByProcessor
from .remove_flag_was_teleported_by_processor import RemoveFlagWasTeleportedByProcessor