__all__ = ['PerformGUIPress']

import logging

# Parent super-class
from pgrpg.core.ecs import Processor, SkipProcessorExecution

# Used components
from core.components.gui_button import GUIButton
from core.components.gui_pressable import Pressable
from core.components.gui_flag_was_pressed import GUIFlagWasPressed

from pgrpg.core.engine import gui_manager

# For creation of events
from pgrpg.core.events.event import Event

# Logger init
logger = logging.getLogger(__name__)

class PerformGUIPress(Processor):
    ''' Based on user input generates commands to controll the entity.

    Input parameters:
        -   events - list of pressed keys passed from the main game loop
        -   add_command_fnc - function for storing commands for later processing

    Involved components:
        -   Controllable

    Related processors:
        -   PerformCommandProcessor - for processing of commands generated by this processor

    What if this processor is disabled?
        -	game cannot be controlled by input peripherals

    Where the processor should be planned?
        -   before PerformCommandProcessor - before processing the commands from this processor
        -   as first of the processors - user input should have priority over AI (Brain)
    '''

    PREREQ = []

    def __init__(self, FNC_ADD_EVENT, FNC_ADD_COMMAND, *args, **kwargs):
        ''' Initiation of NewInputProcessor processor.

        Parameters:
            :param add_command_fnc: Reference to the function that adds command to the command queue.
            :param add_command_fnc: reference
        '''
        super().__init__(*args, **kwargs)

        # Reference to function for adding to command queue
        self.add_command_fnc = FNC_ADD_COMMAND

        # Reference to function for adding an event to event queue
        self.add_event_fnc = FNC_ADD_EVENT



    def process(self, *args, **kwargs):
        ''' Process entities having Controllable component. Read user
        input and generate corresponding commands.
        '''
        try:
            super().process(*args, **kwargs)
        except SkipProcessorExecution:
            return


        # Extract events and keys from parameter kwargs
        # currently only keys are used but events might be usefull as well for mouse later
        events = kwargs.get('events', [])
        dt = kwargs['dt']

        # Get all entities that are controllable - not necesserilly moveable as the input can be for static entity theoretically
        for ent, (butt, pressable) in self.world.get_components(GUIButton, Pressable):

            for event in events:
                
                if event.type == gui_manager.pygame_gui.UI_BUTTON_PRESSED:

                    if event.ui_element == butt.button:

                        # Option 1- Add commands to the command queue - command processor necessary for processing
                        for cmd in pressable.cmds:

                            self.add_command_fnc(
                                cmd=cmd,
                                orig_entity_id=ent 
                            )

                            logger.info(f'({self.cycle}) - Entity {ent} - "{cmd=}" sent to the command manager - from button press.')

                        # Option 2 - Generate new event - event processor necessary for event processing
                        self.add_event_fnc(Event('ON_BUTTON_PRESSED', ent, None, params={"name": butt.name}))
                        logger.info(f'({self.cycle}) - Entity {ent} has generated new event.')

                        # Option 3 - Generate a flag - do not forget to remove the flag by the end of the cycle
                        self.world.add_component(ent, GUIFlagWasPressed())
                        logger.info(f'({self.cycle}) - Entity {ent} has generated GUIFlagWasPressed.')


                gui_manager.process_events(event)

        gui_manager.update(dt)
        gui_manager.draw_gui()

    def pre_save(self):
        ''' Prepare processor for serialization by disabling links to 
        non-serializable components (none)
        '''
        pass

    def post_load(self):
        ''' Reconfigure the processor after de-serialization by attaching
        the removed references again.
        '''
        pass

    def finalize(self, *args, **kwargs):
        ''' Method called when closing the game. Put all necessary statements 
        such as closing of files/resources here, if necessary.
        '''
        pass
